services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - CONN_STR=mongodb://user:pass@mongodb
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    depends_on:
        - mongodb
    volumes:
      - ".data:/.data"
      - ".env:/.env"
    ports:
      - '8081:8081'

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    depends_on:
      - backend
#      - frontend
    volumes:
      - ./nginx/ssl_nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /data/letsencrypt:/data/letsencrypt

  minio:
    image: elestio/minio:latest
    restart: always
    dns:
      - 8.8.8.8
    volumes:
      - ./volumes/minio/data:/minio/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_BROWSER_REDIRECT_URL=http://127.0.0.1:9001
      - MINIO_SERVER_URL=http://127.0.0.1:9000
    command: server --address ":9000" --console-address ":9001" /data

  postgres:
    # image: ankane/pgvector:v0.3.1
    # image: postgis/postgis/13-3.1-alpine
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: db_main
      POSTGRES_USER: db_main
      POSTGRES_PASSWORD: db_main
      PGUSER: db_main
      PGPASSWORD: db_main
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      # TODO remove in production
      - "5432:5432"
    labels:
      - "autoheal=true"
    restart: unless-stopped
    volumes:
      - ./extra/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volumes/pg/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 4000M